/**
 * Export the WHOLE seeded category tree with its three display names into
 * `category_translations.json` at the repository root, for the frontend and
 * localization teams.
 *
 * GENERATED, never hand-edited. It is built from the same modules the seeds
 * write from — the translation table (`category-names.seed.ts`), the roots and
 * buyer buckets (`catalog-reference.seed.ts`) and the subcategory taxonomy
 * (`subcategory-taxonomy.seed.ts`) — so the file cannot drift from what a fresh
 * database would contain. To change a translation, edit
 * `src/prisma/seed-data/category-names.seed.ts` and re-run this.
 *
 * It reads NO database: the export describes the seeded taxonomy, not one
 * environment's live rows (an admin-created category exists in exactly one
 * database and does not belong in a checked-in reference file).
 *
 * Run:  npm run export:category-translations
 */
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import {
  SEED_CATEGORIES,
  SEED_OTHER_CATEGORIES,
  SEED_ROOT_CATEGORIES,
} from '../src/prisma/seed-data/catalog-reference.seed';
import {
  CATEGORY_NAMES,
  localizedNamesFor,
} from '../src/prisma/seed-data/category-names.seed';
import { TAXONOMY } from '../src/prisma/seed-data/subcategory-taxonomy.seed';

/** The fallback bucket — parentless, parked at level 1, not seller-selectable. */
const UNCATEGORIZED_ID = 'cat_uncategorized';

interface ExportedCategory {
  id: string;
  slug: string;
  parentId: string | null;
  level: number;
  name_ru: string;
  name_uz: string;
  name_en: string;
  children?: ExportedCategory[];
}

/** One flat record, before the tree is assembled. */
interface FlatCategory extends Omit<ExportedCategory, 'children'> {
  /** Canonical label, used only to fall back when a translation is missing. */
  canonicalName: string;
}

const flat: FlatCategory[] = [];
const seen = new Set<string>();

function add(
  id: string,
  parentId: string | null,
  level: number,
  canonicalName: string,
): void {
  // The seeds intentionally overlap (a root may appear both in
  // SEED_ROOT_CATEGORIES and as a TAXONOMY parent); first writer wins, so the
  // authoritative list for each kind of node is the one visited first below.
  if (seen.has(id)) return;
  seen.add(id);
  const names = localizedNamesFor(id, canonicalName);
  flat.push({
    id,
    slug: id,
    parentId,
    level,
    name_ru: names.nameRu,
    name_uz: names.nameUz,
    name_en: names.nameEn,
    canonicalName,
  });
}

// ── Level 0: the roots the seller bot lists first ───────────────────────────
for (const root of SEED_ROOT_CATEGORIES) add(root.id, null, 0, root.name);

// The fallback bucket. Parentless but level 1 — see the note in seed.ts on why
// it must not appear as a root a seller can pick.
add(UNCATEGORIZED_ID, null, 1, 'Uncategorized');

// ── Level 1: the 12 buyer-grid buckets ──────────────────────────────────────
for (const bucket of SEED_CATEGORIES) {
  add(bucket.id, bucket.parentId, bucket.level, bucket.name);
}

// ── Level 1: the subcategories a seller actually files a listing under ──────
for (const group of TAXONOMY) {
  for (const sub of group.subs) add(sub.slug, group.parentId, 1, sub.name);
}

// ── Level 1: the admin-managed "Другое" catalogue ───────────────────────────
for (const child of SEED_OTHER_CATEGORIES) add(child.id, 'other', 1, child.name);

/** Nest the flat rows; children ordered by their English name for readability. */
function buildTree(rows: FlatCategory[]): ExportedCategory[] {
  const byId = new Map<string, ExportedCategory>();
  for (const row of rows) {
    const { canonicalName: _canonical, ...node } = row;
    byId.set(row.id, { ...node, children: [] });
  }
  const roots: ExportedCategory[] = [];
  for (const row of rows) {
    const node = byId.get(row.id)!;
    const parent = row.parentId ? byId.get(row.parentId) : undefined;
    if (parent) parent.children!.push(node);
    else roots.push(node);
  }
  // Drop the empty `children` arrays — a leaf reads better without one.
  for (const node of byId.values()) {
    if (node.children!.length === 0) delete node.children;
    else node.children!.sort((a, b) => a.name_en.localeCompare(b.name_en));
  }
  return roots.sort((a, b) => a.name_en.localeCompare(b.name_en));
}

const tree = buildTree(flat);
const untranslated = flat
  .filter((c) => !Object.prototype.hasOwnProperty.call(CATEGORY_NAMES, c.id))
  .map((c) => c.id);

const payload = {
  $comment:
    'GENERATED by Backend/scripts/export-category-translations.ts — do not ' +
    'edit by hand. Source of truth: ' +
    'Backend/src/prisma/seed-data/category-names.seed.ts. Regenerate with ' +
    '`npm run export:category-translations` in Backend/.',
  languages: ['ru', 'uz', 'en'],
  note:
    'Uzbek is LATIN script. `id` is the stable primary key AND the slug — it ' +
    'never changes when a name is translated or renamed. level 0 = vehicle ' +
    'root, level 1 = buyer bucket / subcategory.',
  totalCategories: flat.length,
  generatedFrom: 'seed data (no database was read)',
  categories: tree,
  /** Flat lookup, for a client that wants id → names without walking the tree. */
  flat: Object.fromEntries(
    flat.map((c) => [
      c.id,
      { name_ru: c.name_ru, name_uz: c.name_uz, name_en: c.name_en },
    ]),
  ),
};

const OUT = resolve(__dirname, '../../category_translations.json');
writeFileSync(OUT, `${JSON.stringify(payload, null, 2)}\n`, 'utf8');

console.log(`Wrote ${flat.length} categories → ${OUT}`);
if (untranslated.length > 0) {
  // Not fatal: such a row falls back to its canonical name in all three
  // languages, which is a visible-but-working state, and the fix is one entry
  // in the translation table.
  console.warn(
    `\n⚠️  ${untranslated.length} categories have NO entry in CATEGORY_NAMES ` +
      `and fell back to their canonical name:\n   ${untranslated.join(', ')}`,
  );
}
