import { NestFactory } from '@nestjs/core';
import 'dotenv/config';
import { Logger, ValidationPipe } from '@nestjs/common';
import { WsAdapter } from '@nestjs/platform-ws';
import { DocumentBuilder, SwaggerModule } from '@nestjs/swagger';
import helmet from 'helmet';
import { AppModule } from './app.module';
import { HttpExceptionFilter } from './common/http-exception.filter';

/**
 * Parse a comma-separated CORS allowlist from CORS_ORIGINS. In production an
 * empty list means "deny all browser origins" (server-to-server and the mobile
 * app are unaffected, since they don't send an Origin the browser enforces).
 */
function parseCorsOrigins(): string[] {
  return (process.env.CORS_ORIGINS ?? '')
    .split(',')
    .map((o) => o.trim())
    .filter(Boolean);
}

/**
 * Last-resort safety net. An uncaught exception or unhandled rejection means
 * the process is in an unknown state — Node will otherwise either crash
 * silently (no log) or, for unhandledRejection, just print a warning and keep
 * running in that unknown state. Log it through Nest's Logger (consistent
 * with the rest of the app, PM2-captured) and exit non-zero so PM2 restarts
 * us cleanly rather than limping on.
 */
function installProcessErrorHandlers(getApp: () => import('@nestjs/common').INestApplication | undefined) {
  const logger = new Logger('Process');

  const fatal = (label: string, err: unknown) => {
    logger.error(
      `${label}: ${err instanceof Error ? err.message : String(err)}`,
      err instanceof Error ? err.stack : undefined,
    );
    const app = getApp();
    // Best-effort graceful close (runs OnModuleDestroy, e.g. stopping the
    // Telegram bot) before exiting; don't let a hung close() block the exit.
    const exit = () => process.exit(1);
    if (app) {
      void app.close().finally(exit);
      setTimeout(exit, 5000).unref();
    } else {
      exit();
    }
  };

  process.on('uncaughtException', (err) => fatal('Uncaught exception', err));
  process.on('unhandledRejection', (reason) => fatal('Unhandled rejection', reason));
}

async function bootstrap() {
  const logger = new Logger('Bootstrap');

  let app: import('@nestjs/common').INestApplication | undefined;
  installProcessErrorHandlers(() => app);

  app = await NestFactory.create(AppModule);

  // Run OnModuleDestroy/OnApplicationShutdown hooks on SIGTERM/SIGINT (PM2
  // restart/redeploy, systemd stop, ctrl-C) — e.g. TelegramService.onModuleDestroy
  // stopping the long-polling bot cleanly instead of leaving it dangling.
  app.enableShutdownHooks();

  // Trust the first hop (Nginx) so req.ip reflects the real client IP instead
  // of the proxy's — required for per-IP throttling (@nestjs/throttler) to key
  // on individual clients rather than bucketing everyone behind Nginx together.
  app.getHttpAdapter().getInstance().set('trust proxy', 1);

  // Security headers. The API serves JSON (and SSE for the AI advisor), so the
  // restrictive CSP defaults don't apply; disable CSP to avoid breaking the
  // mobile client and keep the other protections (HSTS, noSniff, etc.).
  app.use(helmet({ contentSecurityPolicy: false }));

  const allowlist = parseCorsOrigins();
  const isProd = process.env.NODE_ENV === 'production';
  app.enableCors({
    // Reflect only allowlisted origins. Requests without an Origin header
    // (native mobile app, server-to-server, curl) are always allowed.
    origin: (origin, callback) => {
      if (!origin || allowlist.includes(origin)) return callback(null, true);
      return callback(null, false);
    },
    credentials: true,
    methods: ['GET', 'POST', 'PATCH', 'PUT', 'DELETE', 'OPTIONS'],
  });
  if (isProd && allowlist.length === 0) {
    logger.warn('CORS_ORIGINS is empty in production — all browser origins will be rejected.');
  }

  app.useGlobalPipes(new ValidationPipe({ whitelist: true, forbidNonWhitelisted: true, transform: true }));
  // Normalize all errors to the frontend `{ code, message }` contract.
  app.useGlobalFilters(new HttpExceptionFilter());
  // Native `ws` adapter powers the /realtime gateway (raw WebSocket protocol).
  app.useWebSocketAdapter(new WsAdapter(app));

  // OpenAPI / Swagger docs at /docs. Read-only: it introspects the existing
  // routes and DTOs (metadata auto-generated by the @nestjs/swagger CLI plugin)
  // and changes no runtime behavior. The 'jwt' bearer scheme is referenced by
  // @ApiBearerAuth('jwt') on the JWT-protected controllers/handlers.
  const swaggerConfig = new DocumentBuilder()
    .setTitle('Mator API')
    .setDescription('REST API Documentation')
    .setVersion('1.0')
    .addBearerAuth(
      { type: 'http', scheme: 'bearer', bearerFormat: 'JWT' },
      'jwt',
    )
    .build();
  const document = SwaggerModule.createDocument(app, swaggerConfig);
  SwaggerModule.setup('docs', app, document);

  // Fire OnModuleDestroy on SIGTERM/SIGINT so the Telegram bot stops its long
  // poll cleanly on restart (otherwise the next instance gets a 409 Conflict).
  app.enableShutdownHooks();
  await app.listen(process.env.PORT ?? 3000);
  logger.log(`Mator backend listening on port ${process.env.PORT ?? 3000}`);
}
bootstrap();
